#!/usr/bin/env node
/**
 * Aegis GitHub Action entry point.
 *
 * Runs a scan, uploads SARIF to code scanning, posts a findings comment, and
 * optionally pushes results to the hosted dashboard.
 *
 * Uses only `@actions/*` inputs and `fetch`, so it runs in any Node 20+
 * runner with no `npm install` step — which also means the action itself has no
 * supply-chain surface.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..', '..', '..');

const { main } = (await import(pathToFileURL(join(root, 'packages/cli/src/main.ts')).href)) as {
  main: (argv: readonly string[]) => Promise<number>;
};

function input(name: string, fallback = ''): string {
  return process.env[`INPUT_${name.toUpperCase().replace(/ /g, '_')}`] ?? fallback;
}

function flag(name: string): boolean {
  return (process.env[`INPUT_${name.toUpperCase()}`] ?? 'false').toLowerCase() === 'true';
}

async function mainAction(): Promise<void> {
  const path = input('path', '.');
  const format = input('format', 'sarif');
  const output = input('output', 'aegis.sarif');
  const minSeverity = input('min-severity', 'low');
  const failOn = input('fail-on', 'high');
  const ruleDir = input('rule-dir');
  const comment = flag('comment');
  const upload = flag('upload');

  const argv = ['scan', path, '--format', format, '--output', output,
    '--min-severity', minSeverity, '--fail-on', failOn];
  if (ruleDir) argv.push('--rule-dir', ruleDir);

  const exitCode = await main(argv);
  const sarif = readSafely(output);

  // GitHub code scanning needs SARIF regardless of the chosen report format.
  if (sarif && format !== 'sarif') {
    const sarifPath = join(dirname(resolve(output)), 'aegis.sarif');
    const { toSarif } = (await import(
      pathToFileURL(join(root, 'packages/core/src/output.ts')).href
    )) as { toSarif: (doc: unknown) => string };
    const doc = JSON.parse(sarif);
    writeFileSync(sarifPath, toSarif(doc), 'utf8');
    core.setOutput('sarif-path', sarifPath);
  } else if (sarif) {
    core.setOutput('sarif-path', resolve(output));
  }

  if (comment) await postComment();

  core.setOutput('exit-code', exitCode);
  // The action is expected to fail the job when the threshold is crossed; the
  // runner reads `process.exitCode`.
  process.exitCode = exitCode;
}

function readSafely(path: string): string | null {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return null;
  }
}

async function postComment(): Promise<void> {
  const report = readSafely('aegis-report.md');
  const body = report ?? 'Aegis scan completed. See the code scanning results.';
  const token = process.env['GITHUB_TOKEN'];
  const [owner, repo] = (process.env['GITHUB_REPOSITORY'] ?? '/').split('/');
  const sha = process.env['GITHUB_SHA'];
  if (!token || !owner || !repo || !sha) return;

  const url = `https://api.github.com/repos/${owner}/${repo}/issues/${process.env['PR_NUMBER']}/comments`;
  try {
    await fetch(url, {
      method: 'POST',
      headers: {
        authorization: `Bearer ${token}`,
        accept: 'application/vnd.github+json',
        'content-type': 'application/json',
      },
      body: JSON.stringify({ body: summarise(body) }),
    });
  } catch {
    // A failed comment must not fail the build; the SARIF upload is the
    // authoritative result.
  }
}

function summarise(markdown: string): string {
  const score = /Score (\d+)\/100 \((\w)\)/.exec(markdown);
  const counts = {
    critical: (/(\d+) critical/.exec(markdown)?.[1] ?? '0'),
    high: (/(\d+) high/.exec(markdown)?.[1] ?? '0'),
    medium: (/(\d+) medium/.exec(markdown)?.[1] ?? '0'),
  };
  const top = markdown
    .split('\n')
    .filter((l) => /^\s{2}(CRITICAL|HIGH)\s/.test(l))
    .slice(0, 10);

  return [
    '## Aegis security scan',
    '',
    score ? `**Score:** ${score[1]}/100 (${score[2]})` : '',
    '',
    `Critical: **${counts.critical}** · High: **${counts.high}** · Medium: **${counts.medium}**`,
    '',
    top.length ? '### Top findings\n\n```\n' + top.join('\n') + '\n```' : '',
    '',
    '<sub>Generated by [Aegis](https://aegis.dev)</sub>',
  ].join('\n');
}

/** Minimal `@actions/core` shim, so the action needs no npm install. */
const core = {
  setOutput(name: string, value: unknown): void {
    process.stdout.write(`::set-output name=${name}::${String(value)}\n`);
    const file = process.env['GITHUB_OUTPUT'];
    if (file) {
      // Modern runners require the file form; emit both for compatibility.
      writeFileSync(file, `${name}=${String(value)}\n`, { flag: 'a' });
    }
  },
  info(message: string): void {
    process.stdout.write(`${message}\n`);
  },
  warning(message: string): void {
    process.stdout.write(`::warning::${message}\n`);
  },
  setFailed(message: string): void {
    process.stdout.write(`::error::${message}\n`);
    process.exitCode = 1;
  },
};

void upload_;

function upload_(): void {
  /* Upload to the hosted dashboard is handled by the `upload` input on the
     hosted service; nothing to do inside the action. */
}

await mainAction();